spring:
  config:
    activate:
      on-profile: test

  datasource:
    username: sa
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true

  h2:
    console:
      enabled: true

  driver:
    path: chromedriver
  jwt:
    secret: sj*&df!3ln28@1~FPo!cM19%L9^V2pA4
    token:
      access-expiration-time: 1000
      refresh-expiration-time: 3600000   # 1시간